# Generated by Django 3.1 on 2022-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofreferences',
            name='type',
            field=models.CharField(default=1, max_length=55, verbose_name='Тип Обращения'),
            preserve_default=False,
        ),
    ]
