# Generated by Django 3.1 on 2022-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listofreferences_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofreferences',
            name='type',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Тип Обращения'),
        ),
    ]
