# Generated by Django 3.1 on 2022-03-31 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUss',
            },
        ),
        migrations.CreateModel(
            name='ImageUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.aboutus')),
            ],
        ),
    ]
