# Generated by Django 3.1 on 2022-04-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220419_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.help')),
            ],
        ),
    ]
