# Generated by Django 3.1 on 2022-03-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutus_imageus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='name',
        ),
    ]
