# Generated by Django 3.1 on 2022-04-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220420_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehelp',
            name='help',
        ),
    ]
