# Generated by Django 3.1 on 2022-03-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
