# Generated by Django 3.1 on 2022-04-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220401_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='image',
            field=models.ImageField(default=7, upload_to='images/Y%/M%/H%'),
            preserve_default=False,
        ),
    ]
