# Generated by Django 3.1 on 2022-04-04 08:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220404_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='main.Size', verbose_name=main.models.Size),
        ),
    ]
