# Generated by Django 3.1 on 2022-04-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
