# Generated by Django 3.1 on 2022-04-04 11:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product', to='main.Color', verbose_name=main.models.Color),
        ),
    ]
