# Generated by Django 3.1 on 2022-04-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220404_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
    ]
