# Generated by Django 3.1 on 2022-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220405_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
