# Generated by Django 3.1 on 2022-04-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image_h')),
                ('description', models.TextField(max_length=200)),
                ('num', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=55)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.type')),
            ],
        ),
    ]
