# Generated by Django 3.1 on 2022-04-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_footer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
