# Generated by Django 3.1 on 2022-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220405_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='email',
        ),
        migrations.AddField(
            model_name='footer',
            name='message',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
