# Generated by Django 3.1 on 2022-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220405_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='message',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
