# Generated by Django 3.1 on 2022-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220405_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('num', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('return_call', models.BooleanField(default=True)),
                ('call', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Number', 'Number')], max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('num_user', models.CharField(max_length=55)),
                ('return_call', models.BooleanField(default=True)),
            ],
        ),
    ]
