# Generated by Django 3.1 on 2022-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_listofreferences_returncall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofreferences',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Data'),
        ),
    ]
