# Generated by Django 3.1 on 2022-04-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_q', models.IntegerField(blank=True, default=True, null=True, verbose_name='Cтоимость')),
                ('quan_sum', models.IntegerField(blank=True, default=True, null=True, verbose_name='Общ Количество:')),
                ('rebate', models.IntegerField(blank=True, default=True, null=True, verbose_name='Скидка')),
                ('sum_r', models.IntegerField(blank=True, default=True, null=True, verbose_name='Итого')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('discounts', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.ManyToManyField(blank=True, related_name='related_cart', to='order.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('New', 'New'), ('Decorated', 'Decorated'), ('Cancelled', 'Cancelled')], default='New', max_length=55, null=True)),
                ('description', models.CharField(blank=True, max_length=55, null=True)),
                ('cart', models.ManyToManyField(related_name='items', to='order.CartItem')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
