# Generated by Django 3.1 on 2022-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
