# Generated by Django 3.1 on 2022-04-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220414_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discounts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
