# Generated by Django 3.1 on 2022-04-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Decorated', 'Decorated'), ('Cancelled', 'Cancelled')], default=1, max_length=55),
            preserve_default=False,
        ),
    ]
