# Generated by Django 3.1 on 2022-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220414_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price_q',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cтоимость'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quan_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общ Количество:'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rebate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sum_r',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
