# Generated by Django 3.1 on 2022-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220414_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
