# Generated by Django 3.1 on 2022-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='old_price_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='price_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='title_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
