# Generated by Django 3.1 on 2022-04-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220415_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size_c',
            new_name='color_c',
        ),
        migrations.AddField(
            model_name='cart',
            name='image_c',
            field=models.ImageField(blank=True, max_length=55, null=True, upload_to=''),
        ),
    ]
