# Generated by Django 3.1 on 2022-04-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220415_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size_c',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='old_price_c',
            field=models.CharField(blank=True, default=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price_c',
            field=models.CharField(blank=True, default=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price_q',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Cтоимость'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quan_sum',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Общ Количество:'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rebate',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sum_r',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='title_c',
            field=models.CharField(blank=True, default=True, max_length=55, null=True),
        ),
    ]
