# Generated by Django 3.1 on 2022-04-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220415_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='color_c',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image_c',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='old_price_c',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price_c',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size_c',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title_c',
        ),
    ]
