# Generated by Django 3.1 on 2022-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20220415_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='color',
        ),
    ]
