# Generated by Django 3.1 on 2022-04-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220415_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
    ]
